version: '2'

networks:
  HealthClaimNetwork:

services:

  ca.insurance.example.com:
    image: hyperledger/fabric-ca:1.4.7
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-insurance
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.insurance.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/0f2b49cde85032dda569ab74b9fc4af8000482d30ecb5fd50cb9030fab0d6e09_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.insurance.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/0f2b49cde85032dda569ab74b9fc4af8000482d30ecb5fd50cb9030fab0d6e09_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/insurance.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerInsurance
    networks:
      - HealthClaimNetwork

  ca.hospital.example.com:
    image: hyperledger/fabric-ca:1.4.7
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-hospital
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.hospital.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/560d7595cf1c015ab3d2523225cb60cf800a2114d1706522252d7920ce69e36b_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.hospital.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/560d7595cf1c015ab3d2523225cb60cf800a2114d1706522252d7920ce69e36b_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/hospital.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerHospital
    networks:
      - HealthClaimNetwork

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer:1.4.7
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/crypto/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/crypto/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/crypto/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/crypto/orderer/tls/ca.crt, /etc/hyperledger/crypto/peerInsurance/tls/ca.crt, /etc/hyperledger/crypto/peerHospital/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderers
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./channel:/etc/hyperledger/configtx
        - ./channel/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/:/etc/hyperledger/crypto/orderer
        - ./channel/crypto-config/peerOrganizations/insurance.example.com/peers/peer0.insurance.example.com/:/etc/hyperledger/crypto/peerInsurance
        - ./channel/crypto-config/peerOrganizations/hospital.example.com/peers/peer0.hospital.example.com/:/etc/hyperledger/crypto/peerHospital
    networks:
      - HealthClaimNetwork

  peer0.insurance.example.com:
    container_name: peer0.insurance.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.insurance.example.com
      - CORE_PEER_LOCALMSPID=InsuranceMSP
      - CORE_PEER_ADDRESS=peer0.insurance.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.insurance.example.com:7051      
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.insurance.example.com:7051
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/insurance.example.com/peers/peer0.insurance.example.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.example.com
    networks:
      - HealthClaimNetwork

  peer1.insurance.example.com:
    container_name: peer1.insurance.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.insurance.example.com
      - CORE_PEER_LOCALMSPID=InsuranceMSP
      - CORE_PEER_ADDRESS=peer1.insurance.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.insurance.example.com:7051      
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.insurance.example.com:7051
    ports:
      - 7056:7051
      - 7058:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/insurance.example.com/peers/peer1.insurance.example.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.example.com
    networks:
      - HealthClaimNetwork

  peer0.hospital.example.com:
    container_name: peer0.hospital.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.hospital.example.com
      - CORE_PEER_LOCALMSPID=HospitalMSP
      - CORE_PEER_ADDRESS=peer0.hospital.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.hospital.example.com:7051      
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hospital.example.com:7051
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/hospital.example.com/peers/peer0.hospital.example.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.example.com
    networks:
      - HealthClaimNetwork

  peer1.hospital.example.com:
    container_name: peer1.hospital.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.hospital.example.com
      - CORE_PEER_LOCALMSPID=HospitalMSP
      - CORE_PEER_ADDRESS=peer1.hospital.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hospital.example.com:7051      
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.hospital.example.com:7051
    ports:
      - 8056:7051
      - 8058:7053
    volumes:
        - ./channel/crypto-config/peerOrganizations/hospital.example.com/peers/peer1.hospital.example.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer.example.com
    networks:
      - HealthClaimNetwork

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4.7
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=hcn-sys-channel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.insurance.example.com:7051
      - CORE_PEER_LOCALMSPID=InsuranceMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/insurance.example.com/peers/peer0.insurance.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/insurance.example.com/peers/peer0.insurance.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/insurance.example.com/peers/peer0.insurance.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/insurance.example.com/users/Admin@insurance.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./channel/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        #- ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.insurance.example.com
      - peer1.insurance.example.com
      - peer0.hospital.example.com
      - peer1.hospital.example.com
    networks:
      - HealthClaimNetwork

